/**
 * Re-export ARCS design tokens from shared. Prefer importing from @/shared/theme/Phase12DesignTokens.
 */
export {
  PRIMARY_BG,
  PRIMARY_BG_FLAT,
  PRIMARY_BG_DARK,
  PRIMARY_BG_LIGHT,
  SECONDARY_BG,
  SECONDARY_TEXT,
  ACCENT_GOLD_GRADIENT,
  ACCENT_GOLD_SOLID,
  ACCENT_GOLD_LIGHT,
  ACCENT_GOLD_DARK,
  TEXT_ON_GOLD,
  TEXT_ON_BLUE,
  TEXT_ON_BLUE_ALT,
  ACCENT_BLUE_GRADIENT,
  TEXT_BLUE_GRADIENT,
  MENU_BAR_GOLD_GRADIENT,
  SLIDER_TRACK_GRADIENT,
  SLIDER_TICK_COLOR,
} from '@/shared/theme/Phase12DesignTokens';
