export const WRITER_OUTLINE_TEXT_TEMPLATE = [
  'WRITER OUTLINE PASTE TEMPLATE',
  '',
  'GUIDANCE',
  '- Title and Premise are optional.',
  '- Acts are optional.',
  '- Paste a structured outline or ordinary prose; ordinary prose is accepted and reviewable.',
  '- Separators may use an ASCII hyphen (-), en dash (–), or em dash (—).',
  '- Page beats may target an individual page or a page range.',
  '',
  'TITLE: Optional story title',
  'PREMISE: Optional one-sentence premise',
  '',
  'ACTS:',
  'Act I - Opening: Establish the ordinary world and the first disruption.',
  'Act II – Confrontation: Escalate the conflict and force a difficult choice.',
  'Act III — Return: Resolve the central conflict and show what changed.',
  '',
  'PAGE BEATS:',
  'Page 1 — Opening image: Introduce the setting and protagonist.',
  'Page 2 - Inciting turn: Disrupt the protagonist’s routine.',
  'Pages 4-5 — Sequence: Let a connected scene span a page range.',
  '',
  'NOTES:',
  'Notes: Preserve the quiet tone and leave room for a wordless reaction.',
  '',
  'INTENTIONALLY UNASSIGNED PROSE:',
  'This intentionally unassigned prose has no structural label so it can be reviewed and placed later.',
  '',
].join('\n');

export const WRITER_OUTLINE_MARKDOWN_TEMPLATE = [
  '# Writer Outline Paste Template',
  '',
  '## Guidance',
  '',
  '- Title and Premise are optional.',
  '- Acts are optional.',
  '- Paste a structured outline or ordinary prose; ordinary prose is accepted and reviewable.',
  '- Separators may use an ASCII hyphen (-), en dash (–), or em dash (—).',
  '- Page beats may target an individual page or a page range.',
  '',
  '## Optional Title and Premise',
  '',
  '**TITLE:** Optional story title',
  '',
  '**PREMISE:** Optional one-sentence premise',
  '',
  '## Optional Acts',
  '',
  '**ACTS:**',
  '',
  '- Act I - Opening: Establish the ordinary world and the first disruption.',
  '- Act II – Confrontation: Escalate the conflict and force a difficult choice.',
  '- Act III — Return: Resolve the central conflict and show what changed.',
  '',
  '## Page Beats',
  '',
  '- Page 1 — Opening image: Introduce the setting and protagonist.',
  '- Page 2 - Inciting turn: Disrupt the protagonist’s routine.',
  '- Pages 4-5 — Sequence: Let a connected scene span a page range.',
  '',
  '## Notes',
  '',
  '**NOTES:** Preserve the quiet tone and leave room for a wordless reaction.',
  '',
  '## Intentionally Unassigned Prose',
  '',
  'This intentionally unassigned prose has no structural label so it can be reviewed and placed later.',
  '',
].join('\n');

export const WRITER_OUTLINE_TEMPLATE_FILES = [
  {
    format: 'text',
    filename: 'writer-outline-template.txt',
    mimeType: 'text/plain;charset=utf-8',
    content: WRITER_OUTLINE_TEXT_TEMPLATE,
  },
  {
    format: 'markdown',
    filename: 'writer-outline-template.md',
    mimeType: 'text/markdown;charset=utf-8',
    content: WRITER_OUTLINE_MARKDOWN_TEMPLATE,
  },
] as const;
